aws_region     = "us-east-1"
ami_id         = "ami-0c7217cdde317cfec"
instance_type  = "t2.micro"
key_name       = "aws_cloud"
ec2_name       = "flask-reporte-app"
input_bucket_name   = "proyecto-csv-entrada"
output_bucket_name  = "proyecto-csv-salida"
dynamodb_table_name = "reportes_table"