aws_region     = "us-east-1"
db_password    = "root"
ami_id         = "ami-0c7217cdde317cfec"
instance_type  = "t2.micro"
key_name       = "aws_cloud"
ec2_name       = "flask-reporte-app"
output_bucket_name = "proyecto-reportes-procesados"