aws_region     = "us-east-1"
ami_id         = "ami-0c7217cdde317cfec"
instance_type  = "t2.micro"
key_name       = "aws_cloud"
ec2_name       = "flask-reporte-app"
input_bucket_name = "proyecto-csv-entrada-2025"
output_bucket_name = "proyecto-reportes-procesados"
dynamodb_table_name = "reportes_table"